name: Backend CI

on:
  push:
    branches: [develop, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Debug Repository
        run: |
          echo "PWD:"
          pwd
          echo "FILES:"
          ls -la
          echo "POM FILES:"
          find . -name "pom.xml"

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build Backend
        run: |
          cd backend/order_table
          mvn clean verify
